name: Run percent.py on commit

on:
  push:
    branches: [ main ]

jobs:
  run-percent:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run percent.py and commit changes
      run: |
        cd tools
        python percent.py
        git config --global user.email "ihor@noleron.com"
        git config --global user.name "Ihor Andreew"
        git add .
        git commit -m "Update percent values"
        git push
