name: Update Percentages

on:
  push:
    branches:
      - master

jobs:
  update_percentages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Percentages
      run: |
        cd tools
        python percent.py
        git config --global user.email "ihor@noleron.com"
        git config --global user.name "Ihor Andreew"
        git add .
        git commit -m "Оновлення відсотків на сайті"
        git push https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/ua-thinking/Starbound.git HEAD:master
