name: Update Percent Values

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run percent.py
      run: |
        cd tools
        python percent.py
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: "Ihor Andreew"
        author_email: "ihor@noleron.com"
        message: "Оновлення відсотків на сайті"
        add: "."
        token: ${{ secrets.MY_GITHUB_TOKEN }}
