name: Auto update and push
on:
  push:
    branches:
      - main
jobs:
  update-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11' # замініть x на версію Python, яку ви використовуєте
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Git pull
        run: git pull
      - name: Run percent.py
        run: python /tools/percent.py # замініть цей шлях на шлях до вашого скрипту percent.py
      - name: Git add and commit
        run: |
          git add .
          git commit -m "Відсотки на сайті"
      - name: Git push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
