name: Create and update translations files

on:
  push:
    branches:
      - main

jobs:
  create-and-update-files:
    name: Створення та оновлення нових файлів
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Видалення старих файлів
      run: |
        rm -f translations/totallabels.json
        rm -f translations/translatedlabels.json

    - name: Створення нових файлів
      working-directory: ./tools
      run: |
        git add __pycache__/json_tools.cpython-310.pyc
        python create_files.py
        python percents.py

    - name: Комміт
      run: |
        git config --global user.name "Ihor Andreew"
        git config --global user.email "ihor@noleron.com"
        git add translations/*
        git commit -m "Оновлення відсотків на сайті"
        git push
