name: Update Translation Progress

on:
  push:
    branches:
      - master

jobs:
  update_translation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run percents.py
        run: python tools/percents.py
      - name: Commit changes
        run: |
          git config --local user.email "ihor@noleron.com"
          git config --local user.name "Ihor Andreew"
          git commit -m "Update translation progress"
