name: Run percents.py and commit changes

on:
  push:
    branches:
      - master

jobs:
  run-percents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run percents.py
        run: |
          cd tools
          python percents.py

      - name: Commit changes
        run: |
          git config --global user.email "ihor@noleron.com"
          git config --global user.name "uandreew"
          git add .
          git commit -m "Оновлення відсотків на сайті"
          git push
