name: Оновлення відсотків на сайті

on:
  push:
    branches:
      - master

jobs:
  generate_percents:
    runs-on: ubuntu-latest
    steps:
      - name: Перевірка репа
        uses: actions/checkout@v2

      - name: Видалення старих файлів
        run: |
          rm -f totallabels.json
          rm -f translatedlabels.json

      - name: Встановлення залежностей
        run: |
          sudo apt-get install -y python3
          pip3 install requests

      - name: Генерація відсотків
        env:
          GITHUB_TOKEN: ${{ secrets.STARBOUND_SECRET }}
        run: |
          cd tools
          python3 create_files.py
          python3 percents.py
          git config --local user.email "ihor@noleron.com"
          git config --local user.name "Ihor Andreew"
          git commit -m "Оновлення відсотків на сайті"
          git push
